name: Publish 📝

on:
  push:
    tags:
     - "*"

jobs:
  build-publish:
    name: Build & Publish
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract Tag Name
      run: echo "TAG_NUMBER=$(git describe --tags | sed 's/v//')" >> $GITHUB_ENV
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Workflow Deps
      run: python -m pip install poetry poetry2setup wheel
    - name: Bump Version
      run: |
        poetry version $TAG_NUMBER
        poetry2setup > setup.py 
    - name: Publish Distribution to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_API_TOKEN
        poetry publish --build