name: Publish 📝

on:
  workflow_dispatch:
  push:
    tags:
     - "*"

jobs:
  build-publish:
    name: Build & Publish
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup HEAD
      run: >- 
        git checkout "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')" &&
        git config --global user.name "${{ github.repository_owner }}" &&
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install workflow deps
      run: >-
        python -m pip install poetry poetry2setup wheel
    - name: Extract tag name
      id: set_tag
      run: echo "::setOutput name=tag::$(echo ${{ github.ref }} | sed 's/v//')"
    - name: Update version in pyproject.toml and generate new setup.py
      run: >-
        poetry version ${{ steps.set_tag.outputs.tag }} &&
        poetry2setup > setup.py &&
        git commit -m "chore: bump up ${{ steps.set_tag.outputs.tag }} version from workflow" &&
        git push
    - name: Publish distribution to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_API_TOKEN
        poetry publish --build