name: Publish 📝

on:
  workflow_dispatch:
  push:
    tags:
     - "*"

jobs:
  build-publish:
    name: Build & Publish
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Git
      run: |
        git config --global user.name "${{github.actor}}" 
        git config --global user.email "${{github.actor}}@users.noreply.github.com" 
    - name: Extract Tag Name
      run: echo "TAG_NAME=$(git describe --tags | sed 's/v//')" >> $GITHUB_ENV
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Workflow Deps
      run: >-
        python -m pip install poetry poetry2setup wheel
    - name: Update version in pyproject.toml and generate new setup.py
      run: |
        poetry version $TAG_NAME 
        poetry2setup > setup.py 
        git add .
        git commit -m "chore: bump up $TAG_NAME version from workflow" 
        git push HEAD:${GITHUB_REF##*/}
    - name: Publish Distribution to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_API_TOKEN
        poetry publish --build