name: Publish 📝

on:
  workflow_dispatch:
  push:
    tags:
     - "*"

jobs:
  build-publish:
    name: Build & Publish
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup HEAD
      run: >- 
        git config --global user.name "${{github.actor}}" &&
        git config --global user.email "${{github.actor}}@users.noreply.github.com" &&
        git checkout "${GITHUB_REF##*/}"
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install workflow deps
      run: >-
        python -m pip install poetry poetry2setup wheel
    - id: set_tag
      name: Extract tag name
      run: echo "tag=$(git describe --tags | sed 's/v//')"
    - name: Update version in pyproject.toml and generate new setup.py
      env:
        TAG_NAME: ${{ steps.set_tag.outputs.tag }}
      run: >-
        poetry version $TAG_NAME &&
        poetry2setup > setup.py &&
        git commit -m "chore: bump up $TAG_NAME version from workflow" &&
        git push
    - name: Publish distribution to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry config pypi-token.pypi $PYPI_API_TOKEN
        poetry publish --build