name: Release 📦

on:
  push:
    tags:
     - "*"

jobs:
  release:
    name: Packaging & Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract Tag Name
        run: echo "TAG_NAME=$(git describe --tags)" >> $GITHUB_ENV
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: "QuotexPy Release ${{ env.TAG_NAME }}.zip"
          exclusions: "*.git*"
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "QuotexPy Release ${{ env.TAG_NAME }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}